# Generated by Django 6.0.2 on 2026-02-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('request_type', models.CharField(blank=True, choices=[('consultanta', 'Consultanță'), ('startup', 'Program STARTUP'), ('incubator', 'Incubator'), ('parteneriate', 'Parteneriate'), ('altele', 'Altele')], max_length=50, verbose_name='Tip solicitare')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('is_read', models.BooleanField(default=False, verbose_name='Citit')),
            ],
            options={
                'verbose_name': 'Solicitare',
                'verbose_name_plural': 'Solicitări',
                'ordering': ['-created_at'],
            },
        ),
    ]
