# Generated by Django 6.0.2 on 2026-02-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EUProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titlu')),
                ('description', models.TextField(verbose_name='Descriere')),
                ('funder', models.CharField(blank=True, max_length=200, verbose_name='Finanțator')),
                ('status', models.CharField(choices=[('active', 'Activ'), ('completed', 'Finalizat')], default='active', max_length=20, verbose_name='Status')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Proiect european',
                'verbose_name_plural': 'Proiecte europene',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagine')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descriere')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Fotografie',
                'verbose_name_plural': 'Galerie foto',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume')),
                ('specialization', models.CharField(max_length=200, verbose_name='Specializare')),
                ('bio', models.TextField(blank=True, verbose_name='Biografie')),
                ('photo', models.ImageField(blank=True, upload_to='mentors/', verbose_name='Foto')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentori',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Logo')),
                ('website_url', models.URLField(blank=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, verbose_name='Descriere')),
                ('partner_type', models.CharField(choices=[('internal', 'Intern'), ('international', 'Internațional')], default='internal', max_length=20, verbose_name='Tip')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
            ],
            options={
                'verbose_name': 'Partener',
                'verbose_name_plural': 'Parteneri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titlu')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('badge', models.CharField(help_text='Ex: Consultanță, Educație, Granturi', max_length=50, verbose_name='Badge')),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome class', max_length=100, verbose_name='Icon CSS class')),
                ('short_description', models.TextField(verbose_name='Descriere scurtă')),
                ('content', models.TextField(help_text='HTML permis', verbose_name='Conținut complet')),
                ('image', models.ImageField(blank=True, upload_to='programs/', verbose_name='Imagine')),
                ('highlight_number', models.CharField(blank=True, help_text='Ex: 4215', max_length=50, verbose_name='Număr evidențiat')),
                ('highlight_text', models.CharField(blank=True, help_text='Ex: consultații oferite', max_length=200, verbose_name='Text evidențiat')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured (full-width)')),
                ('cta_text', models.CharField(blank=True, max_length=100, verbose_name='Text buton CTA')),
                ('cta_url', models.URLField(blank=True, verbose_name='URL buton CTA')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programe',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Ex: consultations, beneficiaries', max_length=100, unique=True, verbose_name='Cheie')),
                ('value', models.CharField(help_text='Ex: 4215, 33.3', max_length=50, verbose_name='Valoare')),
                ('suffix', models.CharField(blank=True, help_text='Ex: +, mil. lei, %', max_length=50, verbose_name='Sufix')),
                ('decimal_places', models.IntegerField(default=0, help_text='Pentru animația data-decimal', verbose_name='Zecimale')),
                ('label', models.CharField(help_text='Ex: consultații oferite', max_length=200, verbose_name='Etichetă')),
                ('icon_class', models.CharField(blank=True, max_length=100, verbose_name='Icon CSS class')),
                ('category', models.CharField(choices=[('impact', 'Impact general'), ('programs', 'Programe'), ('ima', 'IMA / Infrastructură'), ('partners', 'Parteneri')], max_length=20, verbose_name='Categorie')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Statistică',
                'verbose_name_plural': 'Statistici',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titlu')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('company_name', models.CharField(max_length=200, verbose_name='Companie')),
                ('category', models.CharField(help_text='Ex: IT & AI, FinTech, Textile', max_length=50, verbose_name='Categorie')),
                ('short_description', models.TextField(help_text='Previzualizare pe pagina principală', verbose_name='Descriere scurtă')),
                ('content', models.TextField(help_text='HTML permis', verbose_name='Conținut complet')),
                ('image', models.ImageField(upload_to='stories/', verbose_name='Imagine')),
                ('quote', models.TextField(blank=True, verbose_name='Citat fondator')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Pe pagina principală')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creării')),
            ],
            options={
                'verbose_name': 'Istorie de succes',
                'verbose_name_plural': 'Istorii de succes',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
