# Generated by Django 5.2.9 on 2026-02-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titlu')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Rezumat')),
                ('content', models.TextField(help_text='HTML permis', verbose_name='Conținut')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Imagine')),
                ('published_date', models.DateField(verbose_name='Data publicării')),
                ('source_url', models.URLField(blank=True, verbose_name='URL sursă')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comunicat',
                'verbose_name_plural': 'Comunicate',
                'ordering': ['-published_date'],
            },
        ),
    ]
