# Generated by Django 6.0.2 on 2026-02-27 11:42

from django.db import migrations


def fix_duplicate_quote(apps, schema_editor):
    import re
    SuccessStory = apps.get_model('pages', 'SuccessStory')
    for story in SuccessStory.objects.all():
        if story.content and '<blockquote>' in story.content:
            story.content = re.sub(r'<blockquote>.*?</blockquote>', '', story.content, flags=re.DOTALL)
            story.save(update_fields=['content'])


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_load_documents'),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_quote, migrations.RunPython.noop),
    ]
