# Generated by Django 6.0.2 on 2026-02-27 11:42

from django.db import migrations


def fix_duplicate_quote(apps, schema_editor):
    SuccessStory = apps.get_model('pages', 'SuccessStory')
    try:
        story = SuccessStory.objects.get(company_name='Ken AI')
    except SuccessStory.DoesNotExist:
        return
    old = '<blockquote>"Visul meu este sa construiesc afaceri care ajuta oamenii sa creasca prin educatie si tehnologie." - Cristian Frunze</blockquote>'
    if old in story.content:
        story.content = story.content.replace(old, '')
        story.save(update_fields=['content'])


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_load_documents'),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_quote, migrations.RunPython.noop),
    ]
