# Generated by Django 5.2.9 on 2026-03-01 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_fix_frunze_duplicate_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Imagine')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Descriere')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.news', verbose_name='Comunicat')),
            ],
            options={
                'verbose_name': 'Imagine comunicat',
                'verbose_name_plural': 'Imagini comunicat',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
