# Generated by Django 5.2.9 on 2026-03-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_newsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titlu')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('cover_image', models.ImageField(upload_to='gallery/events/', verbose_name='Imagine copertă')),
                ('description', models.TextField(blank=True, verbose_name='Descriere')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Data evenimentului')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Eveniment galerie',
                'verbose_name_plural': 'Evenimente galerie',
                'ordering': ['order', '-event_date'],
            },
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pages.galleryevent', verbose_name='Eveniment'),
        ),
    ]
