# Generated by Django 6.0.2 on 2026-03-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_galleryevent_galleryphoto_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Denumire'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ro',
            field=models.CharField(max_length=500, null=True, verbose_name='Denumire'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Denumire'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_uk',
            field=models.CharField(max_length=500, null=True, verbose_name='Denumire'),
        ),
        migrations.AddField(
            model_name='euproject',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='euproject',
            name='description_ro',
            field=models.TextField(null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='euproject',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='euproject',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='euproject',
            name='funder_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Finanțator'),
        ),
        migrations.AddField(
            model_name='euproject',
            name='funder_ro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Finanțator'),
        ),
        migrations.AddField(
            model_name='euproject',
            name='funder_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Finanțator'),
        ),
        migrations.AddField(
            model_name='euproject',
            name='funder_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Finanțator'),
        ),
        migrations.AddField(
            model_name='euproject',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='euproject',
            name='title_ro',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='euproject',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='euproject',
            name='title_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='galleryevent',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='galleryevent',
            name='description_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='galleryevent',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='galleryevent',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='galleryevent',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='galleryevent',
            name='title_ro',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='galleryevent',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='galleryevent',
            name='title_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='caption_ro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='caption_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='caption_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Biografie'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='bio_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Biografie'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Biografie'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='bio_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Biografie'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nume'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='name_ro',
            field=models.CharField(max_length=200, null=True, verbose_name='Nume'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Nume'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Nume'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='specialization_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Specializare'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='specialization_ro',
            field=models.CharField(max_length=200, null=True, verbose_name='Specializare'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='specialization_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Specializare'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='specialization_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Specializare'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(help_text='HTML permis', null=True, verbose_name='Conținut'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ro',
            field=models.TextField(help_text='HTML permis', null=True, verbose_name='Conținut'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(help_text='HTML permis', null=True, verbose_name='Conținut'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uk',
            field=models.TextField(help_text='HTML permis', null=True, verbose_name='Conținut'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_en',
            field=models.TextField(blank=True, null=True, verbose_name='Rezumat'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Rezumat'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Rezumat'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Rezumat'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ro',
            field=models.CharField(max_length=500, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uk',
            field=models.CharField(max_length=500, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='caption_ro',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='caption_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='caption_uk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Descriere'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nume'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ro',
            field=models.CharField(max_length=200, null=True, verbose_name='Nume'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Nume'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Nume'),
        ),
        migrations.AddField(
            model_name='program',
            name='badge_en',
            field=models.CharField(help_text='Ex: Consultanță, Educație, Granturi', max_length=50, null=True, verbose_name='Badge'),
        ),
        migrations.AddField(
            model_name='program',
            name='badge_ro',
            field=models.CharField(help_text='Ex: Consultanță, Educație, Granturi', max_length=50, null=True, verbose_name='Badge'),
        ),
        migrations.AddField(
            model_name='program',
            name='badge_ru',
            field=models.CharField(help_text='Ex: Consultanță, Educație, Granturi', max_length=50, null=True, verbose_name='Badge'),
        ),
        migrations.AddField(
            model_name='program',
            name='badge_uk',
            field=models.CharField(help_text='Ex: Consultanță, Educație, Granturi', max_length=50, null=True, verbose_name='Badge'),
        ),
        migrations.AddField(
            model_name='program',
            name='content_en',
            field=models.TextField(help_text='HTML permis', null=True, verbose_name='Conținut complet'),
        ),
        migrations.AddField(
            model_name='program',
            name='content_ro',
            field=models.TextField(help_text='HTML permis', null=True, verbose_name='Conținut complet'),
        ),
        migrations.AddField(
            model_name='program',
            name='content_ru',
            field=models.TextField(help_text='HTML permis', null=True, verbose_name='Conținut complet'),
        ),
        migrations.AddField(
            model_name='program',
            name='content_uk',
            field=models.TextField(help_text='HTML permis', null=True, verbose_name='Conținut complet'),
        ),
        migrations.AddField(
            model_name='program',
            name='cta_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Text buton CTA'),
        ),
        migrations.AddField(
            model_name='program',
            name='cta_text_ro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Text buton CTA'),
        ),
        migrations.AddField(
            model_name='program',
            name='cta_text_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Text buton CTA'),
        ),
        migrations.AddField(
            model_name='program',
            name='cta_text_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Text buton CTA'),
        ),
        migrations.AddField(
            model_name='program',
            name='highlight_text_en',
            field=models.CharField(blank=True, help_text='Ex: consultații oferite', max_length=200, null=True, verbose_name='Text evidențiat'),
        ),
        migrations.AddField(
            model_name='program',
            name='highlight_text_ro',
            field=models.CharField(blank=True, help_text='Ex: consultații oferite', max_length=200, null=True, verbose_name='Text evidențiat'),
        ),
        migrations.AddField(
            model_name='program',
            name='highlight_text_ru',
            field=models.CharField(blank=True, help_text='Ex: consultații oferite', max_length=200, null=True, verbose_name='Text evidențiat'),
        ),
        migrations.AddField(
            model_name='program',
            name='highlight_text_uk',
            field=models.CharField(blank=True, help_text='Ex: consultații oferite', max_length=200, null=True, verbose_name='Text evidențiat'),
        ),
        migrations.AddField(
            model_name='program',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='Descriere scurtă'),
        ),
        migrations.AddField(
            model_name='program',
            name='short_description_ro',
            field=models.TextField(null=True, verbose_name='Descriere scurtă'),
        ),
        migrations.AddField(
            model_name='program',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Descriere scurtă'),
        ),
        migrations.AddField(
            model_name='program',
            name='short_description_uk',
            field=models.TextField(null=True, verbose_name='Descriere scurtă'),
        ),
        migrations.AddField(
            model_name='program',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='program',
            name='title_ro',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='program',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='program',
            name='title_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='label_en',
            field=models.CharField(help_text='Ex: consultații oferite', max_length=200, null=True, verbose_name='Etichetă'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='label_ro',
            field=models.CharField(help_text='Ex: consultații oferite', max_length=200, null=True, verbose_name='Etichetă'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='label_ru',
            field=models.CharField(help_text='Ex: consultații oferite', max_length=200, null=True, verbose_name='Etichetă'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='label_uk',
            field=models.CharField(help_text='Ex: consultații oferite', max_length=200, null=True, verbose_name='Etichetă'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='suffix_en',
            field=models.CharField(blank=True, help_text='Ex: +, mil. lei, %', max_length=50, null=True, verbose_name='Sufix'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='suffix_ro',
            field=models.CharField(blank=True, help_text='Ex: +, mil. lei, %', max_length=50, null=True, verbose_name='Sufix'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='suffix_ru',
            field=models.CharField(blank=True, help_text='Ex: +, mil. lei, %', max_length=50, null=True, verbose_name='Sufix'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='suffix_uk',
            field=models.CharField(blank=True, help_text='Ex: +, mil. lei, %', max_length=50, null=True, verbose_name='Sufix'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='category_en',
            field=models.CharField(help_text='Ex: IT & AI, FinTech, Textile', max_length=50, null=True, verbose_name='Categorie'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='category_ro',
            field=models.CharField(help_text='Ex: IT & AI, FinTech, Textile', max_length=50, null=True, verbose_name='Categorie'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='category_ru',
            field=models.CharField(help_text='Ex: IT & AI, FinTech, Textile', max_length=50, null=True, verbose_name='Categorie'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='category_uk',
            field=models.CharField(help_text='Ex: IT & AI, FinTech, Textile', max_length=50, null=True, verbose_name='Categorie'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='company_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Companie'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='company_name_ro',
            field=models.CharField(max_length=200, null=True, verbose_name='Companie'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='company_name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Companie'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='company_name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Companie'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='content_en',
            field=models.TextField(help_text='HTML permis', null=True, verbose_name='Conținut complet'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='content_ro',
            field=models.TextField(help_text='HTML permis', null=True, verbose_name='Conținut complet'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='content_ru',
            field=models.TextField(help_text='HTML permis', null=True, verbose_name='Conținut complet'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='content_uk',
            field=models.TextField(help_text='HTML permis', null=True, verbose_name='Conținut complet'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='quote_en',
            field=models.TextField(blank=True, null=True, verbose_name='Citat fondator'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='quote_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Citat fondator'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='quote_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Citat fondator'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='quote_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Citat fondator'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='short_description_en',
            field=models.TextField(help_text='Previzualizare pe pagina principală', null=True, verbose_name='Descriere scurtă'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='short_description_ro',
            field=models.TextField(help_text='Previzualizare pe pagina principală', null=True, verbose_name='Descriere scurtă'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='short_description_ru',
            field=models.TextField(help_text='Previzualizare pe pagina principală', null=True, verbose_name='Descriere scurtă'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='short_description_uk',
            field=models.TextField(help_text='Previzualizare pe pagina principală', null=True, verbose_name='Descriere scurtă'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='title_ro',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='title_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='Titlu'),
        ),
    ]
