# Generated by Django 6.0.2 on 2026-03-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_document_title_en_document_title_ro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('planuri', 'Planuri'), ('rapoarte', 'Rapoarte'), ('declaratii', 'Declarații'), ('achizitii_planuri', 'Achiziții — Planuri'), ('achizitii_anunturi', 'Achiziții — Anunțuri'), ('achizitii_rapoarte', 'Achiziții — Rapoarte')], max_length=30, verbose_name='Categorie'),
        ),
    ]
